swagger: "2.0"

info:
  title: "HA(high availability) ETA min service"
  version: "0.0.1"

host: "{{.Host}}"

basePath: /api/v1

produces:
- application/json

consumes:
- text/plain

paths:
  /eta/min:
    get:
      operationId: getEtaMin
      description: |
        Returns min ETA value
      parameters:
      - name: lat
        in: query
        type: number
        format: float64
        required: true
        minimum: -90.0
        maximum: 90.0
        description: Latitude
      - name: lng
        in: query
        type: number
        format: float64
        required: true
        minimum: -180
        maximum: 180
        description: Longitude

      responses:
        200:
          description: ETA min value
          schema:
            type: number
            format: uint64
